# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=64)),
                ('content_level', models.CharField(choices=[('0', 'No text'), ('25', 'Quarter of text'), ('50', 'Half of text'), ('75', 'Three quarters of text'), ('100', 'Full text')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('indicator', models.CharField(max_length=40)),
                ('summarized', models.TextField()),
                ('keywords', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='parse_wiki.Article')),
            ],
        ),
    ]
